"""add partial unique index for active groups and year

Revision ID: 3c169aa89ce3
Revises: d52cd7d1a7c8
Create Date: 2026-08-27 13:58:56.253930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c169aa89ce3'
down_revision: Union[str, Sequence[str], None] = 'd52cd7d1a7c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('groups_title_key'), 'groups', type_='unique')
    op.create_index(op.f('ix_groups_title'), 'groups', ['title'], unique=False)
    op.create_index('uq_active_group_title', 'groups', ['title', 'year'], unique=True, postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_group_title', table_name='groups', postgresql_where=sa.text('is_active = true'))
    op.drop_index(op.f('ix_groups_title'), table_name='groups')
    op.create_unique_constraint(op.f('groups_title_key'), 'groups', ['title'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
