"""change telegram_id to string

Revision ID: 46c4fce000df
Revises: 3c169aa89ce3
Create Date: 2026-08-29 22:58:50.413270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46c4fce000df'
down_revision: Union[str, Sequence[str], None] = '3c169aa89ce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'telegram_id',
               existing_type=sa.String(length=255),
               type_=sa.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
