"""del duplicate confirmed on User

Revision ID: 76a3cf532b1e
Revises: 46c4fce000df
Create Date: 2026-08-29 23:22:24.210604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76a3cf532b1e'
down_revision: Union[str, Sequence[str], None] = '46c4fce000df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_confirmed'), 'users', ['confirmed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_confirmed'), table_name='users')
    # ### end Alembic commands ###
