"""create fio virutal column on User model

Revision ID: b1b73bd00c5a
Revises: 76a3cf532b1e
Create Date: 2026-09-13 11:54:53.796790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1b73bd00c5a'
down_revision: Union[str, Sequence[str], None] = '76a3cf532b1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Включаем расширение pg_trgm ДО создания GIN-индекса
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")

    op.add_column('users', sa.Column('fio', sa.String(length=105), sa.Computed("name || ' ' || surname", persisted=True), nullable=False))
    op.drop_index(op.f('ix_users_confirmed'), table_name='users')
    op.create_index('idx_users_fio_trgm', 'users', ['fio'], unique=False, postgresql_ops={'fio': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index('idx_users_fio_trgm', table_name='users', postgresql_ops={'fio': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_users_confirmed'), 'users', ['confirmed'], unique=False)
    op.drop_column('users', 'fio')
    # ### end Alembic commands ###
