"""add created_date to groups

Revision ID: d52cd7d1a7c8
Revises: 05a1fb3ad9d5
Create Date: 2026-08-25 01:15:37.027516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd52cd7d1a7c8'
down_revision: Union[str, Sequence[str], None] = '05a1fb3ad9d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'created_date')
    # ### end Alembic commands ###
